### ISSUE TITLE
SIGSEGV to select, C-g to cancel wcsle

### ISSUE THREAD

**Issue by dvorka** [dvorka/hstr#96]
hh dies when searching a specific string due to this message:

Program received signal SIGSEGV, Segmentation fault.to select, C-g to cancel
wcslen () at ../sysdeps/x86_64/wcslen.S:24

Version 1.2-1 from http://www.clfh.de/debian/

--------------------------------------------------------------------------------------------------------

(gdb) backtrace
#0  wcslen () at ../sysdeps/x86_64/wcslen.S:24
#1  0x00007ffff7136bf4 in __wcsrtombs (dst=dst@entry=0x0,
src=src@entry=0x7fffffffd540, len=len@entry=0,
    ps=ps@entry=0x7fffffffd530) at wcsrtombs.c:73
#2  0x00007ffff70e49da in _IO_vfprintf_internal
(s=s@entry=0x7fffffffd9c0, format=<optimized out>,
    format@entry=0x605a80 "
The%20Structure%20of%20Goliath%20(Gentrification%20in%20South%20Korea).mov|",

    ap=ap@entry=0x7fffffffdb68) at vfprintf.c:1656
#3  0x00007ffff718d585 in ___vsnprintf_chk (um/bericht/attexvorlage
    s=0x850e30 " Thesum The\\ Structure\\ of\\ Goliath\\
\\(Gentrification\\ in\\ South\\ Korea\\).mov ",
    maxlen=<optimized out>, flags=1, slen=<optimized out>,
    format=0x605a80 "
The%20Structure%20of%20Goliath%20(Gentrification%20in%20South%20Korea).mov|",

    args=0x7fffffffdb68) at vsnprintf_chk.c:63
#4  0x00007ffff7683346 in _nc_printf_string () from
/lib/x86_64-linux-gnu/libncurses.so.5
#5  0x00007ffff767edaf in vwprintw () from
/lib/x86_64-linux-gnu/libncurses.so.5
#6  0x00007ffff767efb5 in mvprintw () from
/lib/x86_64-linux-gnu/libncurses.so.5
#7  0x0000000000403339 in ?? ()
#8  0x000000000040367c in ?? ()
#9  0x0000000000403c79 in ?? ()h
#10 0x0000000000404326 in ?? ()
#11 0x0000000000401888 in ?? ()
#12 0x00007ffff70bbb45 in __libc_start_main (main=0x401820, argc=1,
argv=0x7fffffffe028, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>,
stack_end=0x7fffffffe018) at libc-start.c:287
#13 0x00000000004018c5 in ?? ()
#14 0x00007fffffffe018 in ?? ()
#15 0x000000000000001c in ?? ()
#16 0x0000000000000001 in ?? ()t queries; queries.reset()'|less
#17 0x00007fffffffe393 in ?? ()
#18 0x0000000000000000 in ?? ()
(gdb)

**Comment by dvorka** [comment]
wcsle explanation:
* http://linux.die.net/man/3/wcslen

**Comment by dvorka** [comment]
Closing this bug as it is not reproducible (not enough information). It's relatively old and I did a number of i18n related fixes. I ready to reopen it if there is more information OR any similar bug pops up.
